const API_BASE = "https://eduadvisor-production.up.railway.app";
const ADMIN_API_KEY = process.env.ADMIN_API_KEY;
if (!ADMIN_API_KEY) { console.error("❌  Falta ADMIN_API_KEY."); process.exit(1); }

const updates = [
  { id: "cmpq2xm3s01xvrn5qvyxfda0q", name: "Colegio Nuestra Señora de la Merced del Divino Maestro", payload: { levels: ["INICIAL","PRIMARIA","SECUNDARIA"], description: "Institución privada católica de Tucumán bajo la advocación de Nuestra Señora de la Merced del Divino Maestro. Ofrece los niveles inicial, primario y secundario con una propuesta que integra la espiritualidad mercedaria y la pedagogía del Divino Maestro con una formación académica de calidad. Una institución con arraigo en la comunidad tucumana y compromiso con la formación integral de sus alumnos." } },
  { id: "cmpq2xmav021urn5qr7o6x1pz", name: "Colegio Don Orione", payload: { levels: ["INICIAL","PRIMARIA","SECUNDARIA"], description: "Institución privada orionista de Tucumán perteneciente a la Pequeña Obra de la Divina Providencia fundada por San Luis Orione. Ofrece los niveles inicial, primario y secundario con una propuesta que integra la formación académica con la atención preferencial a los más vulnerables. Su carisma orionista de caridad y servicio se traduce en una educación abierta e inclusiva en el corazón del noroeste argentino." } },
  { id: "cmpq2xlxq01uirn5qfhpeoexr", name: "Colegio e Instituto Nuestra Señora de Montserrat", payload: { levels: ["INICIAL","PRIMARIA","SECUNDARIA"], description: "Institución privada benedictina de Tucumán bajo la advocación de Nuestra Señora de Montserrat, patrona de Cataluña. Ofrece los niveles inicial, primario y secundario con la espiritualidad benedictina del ora et labora y la devoción a la Virgen Negra de Montserrat. Una institución con identidad benedictina y europea arraigada en la comunidad del noroeste argentino." } },
  { id: "cmpq2xm9l0218rn5qbi3pqy75", name: "Colegio Giosué Carducci", payload: { levels: ["INICIAL","PRIMARIA","SECUNDARIA"], description: "Institución privada ítalo-argentina de Tucumán que lleva el nombre del poeta italiano Giosué Carducci, Premio Nobel de Literatura 1906. Ofrece los niveles inicial, primario y secundario con una propuesta bilingüe español-italiano que celebra el vínculo cultural entre Italia y Tucumán. Una institución con identidad transatlántica que honra la herencia italiana en la cultura del noroeste argentino." } },
  { id: "cmpq2xlx701u7rn5q2lq4qbv0", name: "Colegio Guillermina Lestón de Guzmán", payload: { levels: ["INICIAL","PRIMARIA","SECUNDARIA"], description: "Institución privada de Tucumán que lleva el nombre de Guillermina Lestón de Guzmán, educadora tucumana vinculada a la historia del sistema educativo de la provincia. Ofrece los niveles inicial, primario y secundario con una propuesta que honra el legado de las grandes maestras del noroeste argentino, formando alumnos con vocación por el saber y el servicio a la comunidad." } },
  { id: "cmpq2xmae021jrn5qcn768qpj", name: "Colegio Las Colinas", payload: { levels: ["INICIAL","PRIMARIA","SECUNDARIA"], description: "Institución privada de Tucumán cuyo nombre evoca las colinas que rodean la ciudad, en el paisaje de transición entre la llanura y las sierras del noroeste. Ofrece los niveles inicial, primario y secundario con una propuesta que celebra la identidad geográfica tucumana. Forma alumnos con arraigo territorial, amor por la naturaleza serrana y preparación académica sólida." } },
  { id: "cmpq2xmgj024wrn5q6skqpsvg", name: "Colegio Las Cumbres", payload: { levels: ["INICIAL","PRIMARIA","SECUNDARIA"], description: "Institución privada de Tucumán cuyo nombre evoca las cumbres del Aconquija y las sierras tucumanas, que enmarcan la ciudad y definen su microclima único. Ofrece los niveles inicial, primario y secundario con una propuesta pedagógica orientada a llevar a cada alumno a su mejor versión. Una institución que forma ciudadanos con ambición, esfuerzo y arraigo en la identidad del jardín de la República." } },
  { id: "cmpq2xm4r01yhrn5qzw513ycd", name: "Colegio Los Cerros · Apdes Tucumán", payload: { levels: ["INICIAL","PRIMARIA","SECUNDARIA"], description: "Institución privada de Tucumán perteneciente a la red APDES, con los niveles inicial, primario y secundario. Su nombre evoca los cerros tucumanos que enmarcan el valle donde se asienta la ciudad. Con la propuesta pedagógica de APDES orientada al aprendizaje activo y la formación en valores, forma alumnos con arraigo en la identidad serrana del noroeste argentino." } },
  { id: "cmpq2xmfa024arn5qq9st53ip", name: "Colegio María Auxiliadora", payload: { levels: ["INICIAL","PRIMARIA","SECUNDARIA"], description: "Institución salesiana femenina de Tucumán dirigida por las Hijas de María Auxiliadora. Ofrece los niveles inicial, primario y secundario con la espiritualidad de Don Bosco y la devoción mariana como ejes formativos. Con presencia salesiana histórica en el noroeste argentino, forma alumnas con sólida preparación académica, fe viva y compromiso con la comunidad tucumana." } },
  { id: "cmpq2xmej023zrn5qjatwjtrt", name: "Colegio María del Rosario", payload: { levels: ["INICIAL","PRIMARIA","SECUNDARIA"], description: "Institución privada católica de Tucumán bajo la advocación de María del Rosario. Ofrece los niveles inicial, primario y secundario con una propuesta que integra la devoción al Rosario con una formación académica actualizada. Con arraigo en la comunidad tucumana, es una institución valorada por su clima espiritual y el acompañamiento personalizado a las familias del noroeste argentino." } },
  { id: "cmpq2xm5801ysrn5q41w8b41y", name: "Colegio María Montessori", payload: { levels: ["INICIAL","PRIMARIA","SECUNDARIA"], description: "Institución privada de Tucumán que lleva el nombre de la educadora italiana María Montessori, pionera de la pedagogía activa y el respeto por los ritmos del niño. Ofrece los niveles inicial, primario y secundario con una propuesta inspirada en el método Montessori que privilegia la autonomía, el aprendizaje por descubrimiento y el ambiente preparado. Una alternativa pedagógica diferenciada en el noroeste argentino." } },
  { id: "cmpq2xme2023orn5qc987qa0u", name: "Colegio Nuestra Señora del Huerto", payload: { levels: ["INICIAL","PRIMARIA","SECUNDARIA"], description: "Institución privada católica de Tucumán bajo la advocación de Nuestra Señora del Huerto. Ofrece los niveles inicial, primario y secundario con una propuesta que une la devoción mariana con una educación integral de calidad. Su imagen del huerto como espacio de cultivo paciente refleja una pedagogía que cuida el crecimiento de cada alumno con atención, amor y constancia en el jardín de la República." } },
  { id: "cmpq2xlw601tlrn5qbk1xgo1i", name: "Colegio Nuestra Señora del Valle", payload: { levels: ["INICIAL","PRIMARIA","SECUNDARIA"], description: "Institución privada católica de Tucumán bajo la advocación de Nuestra Señora del Valle, patrona de Catamarca y venerada en todo el noroeste argentino. Ofrece los niveles inicial, primario y secundario con una propuesta que integra la devoción a la Virgen del Valle con una formación académica sólida. Una institución con profunda raíz devocional en el corazón del noroeste." } },
  { id: "cmpq2xm6r01zprn5qvqlcebo5", name: "Colegio Nueva Concepción", payload: { levels: ["INICIAL","PRIMARIA","SECUNDARIA"], description: "Institución privada de Tucumán con los niveles inicial, primario y secundario. El Colegio Nueva Concepción propone una pedagogía renovada orientada al desarrollo de competencias para el siglo XXI. Su nombre evoca la apertura a nuevas formas de concebir la educación, formando alumnos preparados para los desafíos de una sociedad en permanente transformación en el noroeste argentino." } },
  { id: "cmpq2xm1m01wnrn5qis81l9aw", name: "Colegio Pucará · Apdes Tucumán", payload: { levels: ["INICIAL","PRIMARIA","SECUNDARIA"], description: "Institución privada de Tucumán perteneciente a la red APDES, cuyo nombre Pucará evoca las fortalezas precolombinas que los pueblos indígenas del noroeste construían en lo alto de los cerros. Ofrece los niveles inicial, primario y secundario con una propuesta que celebra la identidad cultural del NOA y los valores de resistencia, comunidad y arraigo en la tierra tucumana." } },
  { id: "cmpq2xmck022rrn5quvjwr0ng", name: "Colegio San Cayetano", payload: { levels: ["INICIAL","PRIMARIA","SECUNDARIA"], description: "Institución privada católica de Tucumán bajo el patronazgo de San Cayetano, patrono del trabajo y el pan. Ofrece los niveles inicial, primario y secundario con una propuesta que integra la fe, el trabajo y la solidaridad como valores fundantes. Su carisma teatino se traduce en una educación comprometida con los sectores más vulnerables y el desarrollo humano integral en el noroeste argentino." } },
  { id: "cmpq2xm0y01wcrn5q4kn1151o", name: "Colegio San José de Calasanz", payload: { levels: ["INICIAL","PRIMARIA","SECUNDARIA"], description: "Institución privada escolapia de Tucumán bajo el patronazgo de San José de Calasanz, primer maestro de escuela popular de la historia. Ofrece los niveles inicial, primario y secundario con la pedagogía calasancia que privilegia la educación de los más pobres como acto de piedad y justicia. Una institución con alma escolapia comprometida con la igualdad de oportunidades educativas en el NOA." } },
  { id: "cmpq2xmd20232rn5q7redrj9j", name: "Colegio Santa María", payload: { levels: ["INICIAL","PRIMARIA","SECUNDARIA"], description: "Institución privada católica de Tucumán bajo la advocación de Santa María, Madre de Dios. Ofrece los niveles inicial, primario y secundario con una propuesta que integra la devoción mariana con una formación académica actualizada. Con arraigo en la comunidad tucumana, es una institución valorada por su clima espiritual y el acompañamiento personalizado a las familias del jardín de la República." } },
  { id: "cmpq2xm3b01xkrn5qf7hc236m", name: "Colegio Santísima Trinidad", payload: { levels: ["INICIAL","PRIMARIA","SECUNDARIA"], description: "Institución privada católica de Tucumán bajo la advocación de la Santísima Trinidad. Ofrece los niveles inicial, primario y secundario con una espiritualidad centrada en el misterio trinitario como modelo de comunión y amor. Una institución que forma alumnos con vida espiritual profunda, solidez académica y espíritu comunitario en la ciudad del Congreso de la Independencia." } },
  { id: "cmpq2xm93020xrn5q44v2mpgu", name: "Colegio Suizo", payload: { levels: ["INICIAL","PRIMARIA","SECUNDARIA"], description: "Institución privada de Tucumán fundada por la comunidad suizo-argentina de la provincia. Ofrece los niveles inicial, primario y secundario con una propuesta que celebra la cultura helvética y sus valores de precisión, trabajo y neutralidad. Una institución con historia en la comunidad tucumana que conecta el rigor suizo con la calidez y la identidad del noroeste argentino." } },
  { id: "cmpq2xm0e01w1rn5q23606731", name: "Colegio Tulio García Fernández", payload: { levels: ["INICIAL","PRIMARIA","SECUNDARIA"], description: "Institución privada de Tucumán que lleva el nombre de Tulio García Fernández, figura relevante de la historia educativa y cultural de la provincia. Ofrece los niveles inicial, primario y secundario con una propuesta que honra su memoria a través de una educación comprometida con la calidad, la identidad tucumana y la formación de ciudadanos comprometidos con su comunidad." } },
  { id: "cmpq2xm2v01x9rn5qf1e6528y", name: "IMEP - Instituto Mixto de Enseñanza Privada", payload: { levels: ["INICIAL","PRIMARIA","SECUNDARIA"], description: "Institución privada mixta de Tucumán con los niveles inicial, primario y secundario. El IMEP ofrece una propuesta educativa integral en un modelo de educación mixta que celebra la diversidad y la complementariedad. Con arraigo en la comunidad tucumana, forma alumnos con apertura al otro, convivencia democrática y preparación académica sólida para los desafíos del siglo XXI." } },
  { id: "cmpq2xmfy024lrn5qi2qc5myl", name: "Instituto 9 de Julio", payload: { levels: ["INICIAL","PRIMARIA","SECUNDARIA"], description: "Institución privada de Tucumán que lleva la fecha del 9 de Julio, día de la Declaración de la Independencia Argentina proclamada en 1816 en el Congreso de Tucumán. Ofrece los niveles inicial, primario y secundario con una propuesta que reivindica el legado histórico de la ciudad que parió la nación argentina. Una institución con identidad patriótica en el corazón de la patria." } },
  { id: "cmpq2xm2c01wyrn5q17rvp8hy", name: "Instituto Arnold Gesell", payload: { levels: ["INICIAL","PRIMARIA","SECUNDARIA"], description: "Institución privada de Tucumán que lleva el nombre del pediatra y psicólogo Arnold Gesell, pionero del estudio del desarrollo infantil en el siglo XX. Ofrece los niveles inicial, primario y secundario con una propuesta basada en el conocimiento científico del desarrollo del niño y el respeto por sus etapas evolutivas. Una institución con identidad pedagógica científica en el noroeste argentino." } },
  { id: "cmpq2xm82020brn5qy1qhsgok", name: "Instituto Cervantes", payload: { levels: ["INICIAL","PRIMARIA","SECUNDARIA"], description: "Institución privada de Tucumán que lleva el nombre de Miguel de Cervantes, autor del Quijote y padre de la lengua española. Ofrece los niveles inicial, primario y secundario con una propuesta que privilegia la literatura, la lengua y el humanismo hispánico. Una institución que inspira a sus alumnos con el legado del escritor más universal de la historia de las letras en español." } },
  { id: "cmpq2xm8l020mrn5q1cmx915b", name: "Instituto Decroly Tucumán", payload: { levels: ["INICIAL","PRIMARIA","SECUNDARIA"], description: "Institución privada de Tucumán que lleva el nombre del médico y pedagogo belga Ovide Decroly, pionero de la educación activa y el aprendizaje globalizado. Ofrece los niveles inicial, primario y secundario con una propuesta inspirada en la pedagogía decroliana que parte de los intereses del niño como eje del aprendizaje. Una institución con identidad pedagógica renovada en el noroeste argentino." } },
  { id: "cmpq2xlze01vfrn5qw1nncw0x", name: "Instituto Dr. Carlos Pellegrini", payload: { levels: ["INICIAL","PRIMARIA","SECUNDARIA"], description: "Institución privada de Tucumán que lleva el nombre del presidente argentino Carlos Pellegrini, fundador del Banco Nación y figura clave de la modernización argentina. Ofrece los niveles inicial, primario y secundario con una propuesta que reivindica los valores del progreso, la institucionalidad y el servicio público. Una institución con identidad histórica en el jardín de la República." } },
  { id: "cmpq2xm6a01zern5q6tujuxh5", name: "Instituto JIM", payload: { levels: ["INICIAL","PRIMARIA","SECUNDARIA"], description: "Institución privada de Tucumán con los niveles inicial, primario y secundario. El Instituto JIM ofrece una propuesta educativa integral con arraigo en la comunidad tucumana. Con compromiso docente y un clima institucional cercano, forma alumnos con valores sólidos y preparación académica para continuar su trayectoria educativa y profesional en el noroeste argentino." } },
  { id: "cmpq2xm5q01z3rn5q3bpaakxm", name: "Instituto John Kennedy - Tucumán", payload: { levels: ["INICIAL","PRIMARIA","SECUNDARIA"], description: "Institución privada de Tucumán que lleva el nombre del presidente estadounidense John F. Kennedy, símbolo del liderazgo, la visión y el compromiso con la democracia. Ofrece los niveles inicial, primario y secundario con una propuesta que privilegia la formación ciudadana, el pensamiento crítico y los valores democráticos. Una institución que inspira a sus alumnos a preguntar qué pueden hacer por su comunidad." } },
  { id: "cmpq2xmby022grn5q31l7n10j", name: "Instituto Juan Pablo II", payload: { levels: ["INICIAL","PRIMARIA","SECUNDARIA"], description: "Institución privada católica de Tucumán que lleva el nombre del Papa Juan Pablo II, el papa viajero que evangelizó a toda una generación y fue proclamado Santo en 2014. Ofrece los niveles inicial, primario y secundario con la espiritualidad del pontificado de Karol Wojtyla centrada en el amor a la Virgen, la defensa de la vida y el diálogo con el mundo contemporáneo." } },
  { id: "cmpq2xlyb01utrn5q2cu7qdpo", name: "Instituto Nicolás Avellaneda", payload: { levels: ["INICIAL","PRIMARIA","SECUNDARIA"], description: "Institución privada de Tucumán que lleva el nombre del presidente argentino Nicolás Avellaneda, tucumano ilustre que gobernó el país entre 1874 y 1880. Ofrece los niveles inicial, primario y secundario con una propuesta que reivindica el legado del presidente que consolidó la organización nacional. Una institución con identidad histórica en la tierra natal del propio Avellaneda." } },
  { id: "cmpq2xm4901y6rn5qj54ltb8t", name: "Instituto Peter Pan", payload: { levels: ["INICIAL","PRIMARIA","SECUNDARIA"], description: "Institución privada de Tucumán que evoca al personaje de J.M. Barrie, Peter Pan, símbolo de la infancia eterna, la imaginación y la aventura. Ofrece los niveles inicial, primario y secundario con una propuesta que celebra la creatividad, el juego y la capacidad de asombro como motores del aprendizaje. Una institución que invita a sus alumnos a no perder nunca el espíritu de la infancia." } },
  { id: "cmpq2xlyy01v4rn5qjyihw7kb", name: "Instituto Privado Almafuerte", payload: { levels: ["INICIAL","PRIMARIA","SECUNDARIA"], description: "Institución privada de Tucumán que lleva el nombre del poeta argentino Almafuerte —Pedro Bonifacio Palacios—, cantor de los humildes y símbolo de la lucha y la esperanza. Ofrece los niveles inicial, primario y secundario con una propuesta que reivindica la cultura popular, el esfuerzo y la dignidad del pueblo argentino. Una institución con alma poética y compromiso social en el noroeste." } },
  { id: "cmpq2xm7d0200rn5qijopxbc4", name: "Instituto Privado San Judas Tadeo", payload: { levels: ["INICIAL","PRIMARIA","SECUNDARIA"], description: "Institución privada de Tucumán bajo el patronazgo de San Judas Tadeo, apóstol de las causas difíciles y patrono de los imposibles. Ofrece los niveles inicial, primario y secundario con una propuesta que celebra la perseverancia, la esperanza y la confianza en que todo es posible con fe y esfuerzo. Una institución que inspira a sus alumnos a no rendirse ante las dificultades." } },
  { id: "cmpq2xlzy01vqrn5qrjhvepr8", name: "Instituto Privado San Pablo", payload: { levels: ["INICIAL","PRIMARIA","SECUNDARIA"], description: "Institución privada de Tucumán bajo el patronazgo del apóstol San Pablo, el gran misionero del cristianismo. Ofrece los niveles inicial, primario y secundario con una espiritualidad paulina orientada al anuncio, la apertura al mundo y la transformación personal. Una institución que forma alumnos con convicción, coraje y vocación apostólica en el noroeste argentino." } },
  { id: "cmpq2xlwq01twrn5qkv8p0fuh", name: "Instituto Privado Tucumán", payload: { levels: ["INICIAL","PRIMARIA","SECUNDARIA"], description: "Institución privada de Tucumán que lleva con orgullo el nombre de la provincia, cuna de la independencia argentina. Ofrece los niveles inicial, primario y secundario con una propuesta profundamente arraigada en la identidad tucumana. En la ciudad que vio nacer la patria en 1816, este instituto forma ciudadanos con conciencia histórica, amor por la cultura del NOA y proyección hacia el futuro." } },
  { id: "cmpq2xmbf0225rn5q04vwnw5x", name: "Instituto Puente", payload: { levels: ["INICIAL","PRIMARIA","SECUNDARIA"], description: "Institución privada de Tucumán con los niveles inicial, primario y secundario. Su nombre, Puente, evoca la conexión, el tránsito y la construcción de vínculos como metáforas del aprendizaje. El Instituto Puente forma alumnos capaces de tender puentes entre el conocimiento y la vida, entre las personas y las ideas, construyendo comunidad en el vibrante noroeste argentino." } },
  { id: "cmpq2xlvi01tarn5qqo8dk0p4", name: "Instituto San Miguel", payload: { levels: ["INICIAL","PRIMARIA","SECUNDARIA"], description: "Institución privada de Tucumán bajo el patronazgo del Arcángel San Miguel, príncipe de la milicia celestial y defensor de la fe. Ofrece los niveles inicial, primario y secundario con una propuesta que integra la espiritualidad micaelina con una formación académica de calidad. Una institución que forma alumnos con fortaleza, valentía y compromiso con los valores del bien en el noroeste argentino." } },
  { id: "cmpq2xmh00257rn5qdmtmyjon", name: "Instituto Técnico Salesiano Lorenzo Massa", payload: { levels: ["SECUNDARIA"], description: "Instituto de educación secundaria técnica salesiano de Tucumán que lleva el nombre del Padre Lorenzo Massa, salesiano fundador del Club Atlético San Lorenzo de Almagro. Ofrece formación técnica especializada con el carisma salesiano de Don Bosco, combinando rigor técnico con formación humana y espiritual. Una institución que responde a las necesidades productivas del noroeste argentino." } },
  { id: "cmpq2xmdj023drn5qejd10iqp", name: "Santa Catalina", payload: { levels: ["INICIAL","PRIMARIA","SECUNDARIA"], description: "Institución privada de Tucumán bajo el patronazgo de Santa Catalina, mártir cristiana y patrona de las universidades y los estudiantes. Ofrece los niveles inicial, primario y secundario con una propuesta que celebra la sabiduría, el estudio y la búsqueda de la verdad como valores centrales de la vida escolar. Una institución con identidad intelectual y espiritual en el jardín de la República argentina." } }
];

async function patchSchool(id, name, payload) {
  const url = `${API_BASE}/v1/schools/id/${id}/profile`;
  const res = await fetch(url, { method: "PATCH", headers: { "content-type": "application/json", "x-admin-key": ADMIN_API_KEY }, body: JSON.stringify(payload) });
  if (res.ok) { console.log(`✅  ${name}`); } else { const body = await res.text(); console.error(`❌  ${name} — HTTP ${res.status}: ${body}`); }
}

console.log(`\n🏫  Curando ${updates.length} colegios de Tucumán...\n`);
for (const { id, name, payload } of updates) { await patchSchool(id, name, payload); }
console.log("\n✨  Listo.\n");
