const API_BASE = "https://eduadvisor-production.up.railway.app";
const ADMIN_API_KEY = process.env.ADMIN_API_KEY;
if (!ADMIN_API_KEY) { console.error("❌  Falta ADMIN_API_KEY."); process.exit(1); }

const updates = [
  { id: "cmq15ui1r006sqi31r09cf2m6", name: "Colegio Grilli Canning", payload: { levels: ["INICIAL","PRIMARIA","SECUNDARIA"], description: "Institución privada de Canning con los niveles inicial, primario y secundario. El Colegio Grilli es una institución familiar con arraigo en la comunidad de Canning, localidad del partido de Esteban Echeverría en pleno crecimiento residencial del sur del Gran Buenos Aires. Con un proyecto educativo de calidad y un clima institucional cálido, forma alumnos con valores sólidos y preparación académica para continuar su trayectoria educativa." } },
  { id: "cmq15ui5p0080qi314fmqzweg", name: "Complejo Educativo Nuestra Tierra", payload: { levels: ["INICIAL","PRIMARIA","SECUNDARIA"], description: "Institución privada de Canning cuyo nombre, Nuestra Tierra, evoca el arraigo, la pertenencia y el vínculo profundo con el entorno natural y comunitario. Ofrece los niveles inicial, primario y secundario con una propuesta pedagógica que celebra la conexión con la tierra y la comunidad como valores fundantes del aprendizaje. Una institución que forma alumnos con identidad, compromiso ambiental y amor por el entorno en la localidad de Canning." } },
  { id: "cmq15uibp009uqi31han4xzes", name: "E.E.S. Nº 15", payload: { levels: ["SECUNDARIA"], description: "Escuela de Educación Secundaria Nº 15 de Canning, institución pública que forma parte del sistema educativo de la provincia de Buenos Aires. Ofrece el nivel secundario con una propuesta orientada a la formación ciudadana y la preparación para la continuación de estudios superiores o la inserción laboral. Una institución comprometida con el acceso igualitario a la educación secundaria para los jóvenes de la localidad de Canning en el partido de Esteban Echeverría." } },
  { id: "cmq15uids00agqi313d6fp44u", name: "Escuela De Educación Secundaria Nº17", payload: { levels: ["SECUNDARIA"], description: "Escuela de Educación Secundaria Nº 17 de Canning, institución pública del sistema educativo provincial. Ofrece el nivel secundario con una propuesta orientada a la formación integral de los jóvenes del partido de Esteban Echeverría. Con docentes comprometidos y una propuesta curricular actualizada, forma ciudadanos críticos, creativos y preparados para los desafíos del mundo contemporáneo en la creciente localidad de Canning." } },
  { id: "cmq15ui4r007pqi31z5ainanp", name: "Escuela Humanos", payload: { levels: ["INICIAL","PRIMARIA","SECUNDARIA"], description: "Institución privada de Canning cuyo nombre, Humanos, pone en el centro de su propuesta pedagógica la humanidad en su dimensión más plena: la dignidad, la empatía y el desarrollo de lo mejor de cada persona. Ofrece los niveles inicial, primario y secundario con un modelo educativo centrado en el ser humano, la convivencia y el desarrollo de competencias emocionales junto con la excelencia académica. Una propuesta diferenciada para la comunidad de Canning." } },
  { id: "cmq15ui2s0073qi31fa9p3rp5", name: "Escuelas Pías de Canning", payload: { levels: ["INICIAL","PRIMARIA","SECUNDARIA"], description: "Institución calasancia de Canning perteneciente a las Escuelas Pías, la congregación fundada por San José de Calasanz —primer maestro de escuela popular de la historia— en el siglo XVII. Ofrece los niveles inicial, primario y secundario con la pedagogía calasancia que privilegia la educación de los más vulnerables como acto de piedad y justicia. Una institución con cinco siglos de historia educativa al servicio de las familias de Canning." } },
  { id: "cmq15uicp00a5qi31c61wx0fd", name: "Instituto de inglés Kindle", payload: { levels: ["INICIAL","PRIMARIA","SECUNDARIA"], description: "Instituto bilingüe privado de Canning cuyo nombre, Kindle (encender en inglés), evoca el fuego del aprendizaje y la pasión por el conocimiento como motores de la educación. Ofrece los niveles inicial, primario y secundario con una propuesta de inmersión en inglés orientada a formar alumnos con fluencia genuina y competencias globales. Una institución que enciende la llama del idioma inglés en el corazón de la comunidad de Canning." } },
  { id: "cmq15ui8q008xqi31ih400f9a", name: "Jardín Nuestra Tierra", payload: { levels: ["INICIAL"], description: "Jardín de infantes del Complejo Educativo Nuestra Tierra de Canning, dedicado a los primeros años de la escolaridad en un entorno vinculado con la naturaleza y el entorno local. Ofrece el nivel inicial con una propuesta pedagógica que celebra la conexión con la tierra, el juego al aire libre y el aprendizaje a través de la exploración del entorno natural. Un primer espacio escolar enraizado en la identidad de la comunidad de Canning." } },
  { id: "cmq15ui3s007eqi31dj933eld", name: "OneSchool Global Buenos Aires Campus", payload: { levels: ["PRIMARIA","SECUNDARIA"], description: "Institución bilingüe privada de Canning perteneciente a la red global OneSchool, con presencia en decenas de países. Ofrece los niveles primario y secundario con una propuesta cristiana y bilingüe de estándar internacional que conecta a sus alumnos con una comunidad educativa global. En la creciente localidad de Canning, el campus Buenos Aires de OneSchool forma ciudadanos del mundo con valores sólidos y competencias globales." } },
  { id: "cmq15ui7p008mqi319te4ce4m", name: "South Creek", payload: { levels: ["INICIAL","PRIMARIA","SECUNDARIA"], description: "Institución bilingüe privada de Canning cuyo nombre evoca los arroyos del sur, paisaje característico del partido de Esteban Echeverría. Ofrece los niveles inicial, primario y secundario con una propuesta bilingüe español-inglés orientada a la formación de ciudadanos con proyección global y arraigo en la identidad de la zona sur del Gran Buenos Aires. Una institución que une el entorno natural de Canning con la apertura al mundo." } },
];

async function patchSchool(id, name, payload) {
  const url = `${API_BASE}/v1/schools/id/${id}/profile`;
  const res = await fetch(url, { method: "PATCH", headers: { "content-type": "application/json", "x-admin-key": ADMIN_API_KEY }, body: JSON.stringify(payload) });
  if (res.ok) { console.log(`✅  ${name}`); } else { const body = await res.text(); console.error(`❌  ${name} — HTTP ${res.status}: ${body}`); }
}

console.log(`\n🏫  Curando ${updates.length} colegios de Canning...\n`);
for (const { id, name, payload } of updates) { await patchSchool(id, name, payload); }
console.log("\n✨  Listo.\n");
