const API_BASE = "https://eduadvisor-production.up.railway.app";
const ADMIN_API_KEY = process.env.ADMIN_API_KEY;
if (!ADMIN_API_KEY) { console.error("❌  Falta ADMIN_API_KEY."); process.exit(1); }

const updates = [
  { id: "cmq6zf181016y12emy6sowpm2", name: "Centro Educativo Alas y Raíces", payload: { levels: ["INICIAL", "PRIMARIA"], description: "Centro educativo privado de Posadas, capital de Misiones, cuyo nombre evoca la dualidad esencial de la educación: las raíces que dan identidad y pertenencia, y las alas que habilitan la libertad y el vuelo. En la tierra de las Misiones Jesuíticas y la selva misionera, ofrece los niveles inicial y primario con propuesta pedagógica que ancla a los niños en su cultura local mientras los proyecta hacia el mundo." } },
  { id: "cmq6zf1cz018h12em3kanyxpt", name: "Colegio del Carmen", payload: { levels: ["INICIAL", "PRIMARIA", "SECUNDARIA"], description: "Institución privada católica de Posadas bajo la advocación de Nuestra Señora del Carmen, patrona de la Marina argentina. Con los tres niveles y formación católica arraigada en la identidad misionera, es parte del tejido educativo y espiritual de la capital provincial. Con comunidad consolidada y vínculo con la Iglesia local, forma alumnos con fe, conocimiento y amor a la cultura misionera en la orilla del río Paraná." } },
  { id: "cmq6zf1gv019p12emc42eerty", name: "Escuela Jardín Modelo", payload: { levels: ["INICIAL"], description: "Jardín de infantes privado modelo de Posadas, capital de Misiones, con propuesta pedagógica actualizada para los más pequeños de la comunidad posadeña. En la capital de la provincia más septentrional del litoral argentino, forma niños con estímulo temprano, juego y afecto en sus primeros años de escolaridad. Una referencia de la educación inicial privada en la ciudad a orillas del Paraná frente a Encarnación, Paraguay." } },
  { id: "cmq6zf1ht01a012empq7p95x3", name: "Instituto Adventista Alta Gracia", payload: { levels: ["INICIAL", "PRIMARIA", "SECUNDARIA"], description: "Instituto de la Iglesia Adventista del Séptimo Día en Posadas con los tres niveles y los valores adventistas de salud integral, amor por la naturaleza y vida en comunidad. En la capital de Misiones, la propuesta adventista de educación holística —que integra cuerpo, mente y espíritu— encuentra resonancia en la cultura misionera que valora la naturaleza y la selva. Una opción para familias que priorizan la formación de valores adventistas en la capital provincial." } },
  { id: "cmq6zf1c1018612em0jo0vnde", name: "Instituto Cristiano República Argentina (ICRA)", payload: { levels: ["INICIAL", "PRIMARIA", "SECUNDARIA"], description: "Instituto cristiano privado de Posadas con los tres niveles y formación basada en los valores del Evangelio y la identidad nacional argentina. ICRA integra la fe cristiana con el compromiso ciudadano y el amor a la patria en la capital de Misiones. Con comunidad activa y propuesta evangélica, forma alumnos con valores sólidos para la vida en la provincia misionera de la selva y el río Paraná." } },
  { id: "cmq6zf172016n12empz9lmj9m", name: "Instituto Génesis", payload: { levels: ["INICIAL", "PRIMARIA", "SECUNDARIA"], description: "Instituto privado de Posadas que lleva el nombre del libro del Génesis bíblico —el inicio, la creación, el origen de todas las cosas. Con los tres niveles y propuesta educativa que celebra el comienzo y el potencial de cada alumno, forma ciudadanos posadeños comprometidos con su tierra misionera. En la capital de Misiones, esta institución ofrece una formación con raíces espirituales y proyección hacia el futuro." } },
  { id: "cmq6zf1a1017k12emw27x7czx", name: "Instituto Inmaculada Concepción - Nivel Inicial y Primario", payload: { levels: ["INICIAL", "PRIMARIA"], description: "Instituto privado de Posadas bajo la advocación de la Inmaculada Concepción, dogma mariano proclamado por Pío IX en 1854. Ofrece los niveles inicial y primario con formación católica y devoción a la Virgen en la capital de Misiones. En una provincia con fuerte herencia jesuítica y devoción popular, es parte del tejido educativo y espiritual de la comunidad posadeña desde los primeros años de escolaridad." } },
  { id: "cmq6zf1ey019312emcnvxrvbf", name: "Instituto Inmaculada Concepción - Nivel Secundario", payload: { levels: ["SECUNDARIA"], description: "Instituto privado secundario de Posadas bajo la advocación de la Inmaculada Concepción. Ofrece el bachillerato completo con formación católica y propuesta académica orientada al ingreso universitario. En la capital de Misiones, con su Universidad Nacional y otras instituciones de educación superior, prepara jóvenes posadeños para continuar estudios superiores con fe y conocimiento en la provincia de las Misiones Jesuíticas." } },
  { id: "cmq6zf1ln01b812embi6qxznq", name: "Instituto Madre de la Misericordia", payload: { levels: ["SECUNDARIA"], description: "Instituto privado secundario de Posadas bajo el carisma de la Madre de la Misericordia, advocación mariana que celebra la compasión y el cuidado de los más vulnerables. Ofrece el bachillerato con formación religiosa y compromiso social en la capital de Misiones. En una provincia con zonas de alta vulnerabilidad social, esta institución forma jóvenes con vocación de servicio y misericordia en la tierra de las Misiones Jesuíticas." } },
  { id: "cmq6zf1jo01am12emxbmn1gam", name: "Instituto Politécnico San Arnoldo Janssen", payload: { levels: ["SECUNDARIA"], description: "Instituto politécnico privado de Posadas bajo el patronazgo de San Arnoldo Janssen, el sacerdote alemán que fundó la Sociedad del Verbo Divino (SVD) en 1875. Los Verbitas tienen presencia histórica en Misiones y toda América Latina como misioneros educadores. Con formación técnica secundaria y el carisma verbita de misión y educación, prepara técnicos para las necesidades productivas de la provincia misionera." } },
  { id: "cmq6zf132015f12emx8jqyen4", name: "Instituto Posadas Educa (IPEd) - Educación Bilingüe", payload: { levels: ["INICIAL", "PRIMARIA", "SECUNDARIA"], description: "Instituto bilingüe privado de Posadas con propuesta de inmersión en inglés desde el nivel inicial. IPEd es una de las instituciones de referencia del bilingüismo en la capital misionera, preparando alumnos para certificaciones internacionales y para la vida en un mundo globalizado. En una provincia limítrofe con Brasil y Paraguay, el bilingüismo tiene una dimensión adicional: la integración con los países del MERCOSUR." } },
  { id: "cmq6zf143015q12emvjal69zl", name: "Instituto Sagrado Corazón de Jesús", payload: { levels: ["INICIAL", "PRIMARIA", "SECUNDARIA"], description: "Instituto privado católico de Posadas bajo la advocación del Sagrado Corazón de Jesús, símbolo del amor misericordioso de Cristo hacia la humanidad. Con los tres niveles y formación religiosa en la capital de Misiones, es parte de la rica tradición católica de una provincia marcada por las Misiones Jesuíticas del siglo XVII. Con comunidad consolidada y vínculo con la Iglesia local, forma alumnos con fe y excelencia en Posadas." } },
  { id: "cmq6zf1dy018s12emlqibcqzo", name: "Instituto San Basilio Magno", payload: { levels: ["INICIAL", "PRIMARIA", "SECUNDARIA"], description: "Instituto privado de Posadas bajo el patronazgo de San Basilio el Grande, padre de la Iglesia oriental del siglo IV cuya regla monástica inspiró el monaquismo occidental. Doctor de la Iglesia Universal, San Basilio es venerado tanto en oriente como en occidente. Con los tres niveles y la rica tradición espiritual y cultural del legado basiliano, esta institución posadeña forma alumnos con profundidad intelectual y fe en la capital misionera." } },
  { id: "cmq6zf1fx019e12ema86uusj5", name: "Instituto San Ignacio de Loyola", payload: { levels: ["INICIAL", "PRIMARIA", "SECUNDARIA"], description: "Instituto privado de Posadas bajo el patronazgo de San Ignacio de Loyola, fundador de la Compañía de Jesús. Los Jesuitas tienen una historia única en Misiones: fundaron las Reducciones del siglo XVII donde convivían con los guaraníes en una experiencia social y educativa única en América. Llevar el nombre de Ignacio en Misiones es honrar ese legado histórico. Con los tres niveles y pedagogía ignaciana, forma alumnos para la excelencia y el servicio en la capital provincial." } },
  { id: "cmq6zf1km01ax12emwfn4nvsk", name: "Instituto San Miguel", payload: { levels: ["INICIAL", "PRIMARIA", "SECUNDARIA"], description: "Instituto privado de Posadas bajo el patronazgo del Arcángel San Miguel, príncipe de los ejércitos celestiales y protector de la Iglesia. Con los tres niveles y formación católica en la capital de Misiones, esta institución forma alumnos con la valentía y el coraje que simboliza San Miguel. En la provincia misionera, con su rica herencia jesuítica y guaraní, el Arcángel Miguel es parte del imaginario espiritual popular de la región." } },
  { id: "cmq6zf164016c12em0m7s4gvs", name: "Instituto Santa María de las Misiones", payload: { levels: ["INICIAL", "PRIMARIA", "SECUNDARIA"], description: "Instituto privado de Posadas cuyo nombre celebra a la Virgen María en el contexto de las Misiones Jesuíticas, donde era venerada como Reina de las Reducciones guaraníes. En Misiones, tierra de las ruinas de San Ignacio y Santa Ana, llevar el nombre de 'Santa María de las Misiones' es una declaración de identidad provincial. Con los tres niveles y formación religiosa, honra el legado jesuítico-guaraní en la capital de la provincia." } },
];

async function patchSchool(id, name, payload) {
  const res = await fetch(`${API_BASE}/v1/schools/id/${id}/profile`, {
    method: "PATCH",
    headers: { "content-type": "application/json", "x-admin-key": ADMIN_API_KEY },
    body: JSON.stringify(payload)
  });
  if (res.ok) { console.log(`✅  ${name}`); }
  else { const b = await res.text(); console.error(`❌  ${name} — HTTP ${res.status}: ${b}`); }
}

console.log(`\n🏫  Curando ${updates.length} colegios de Posadas...\n`);
for (const { id, name, payload } of updates) { await patchSchool(id, name, payload); }
console.log("\n✨  Listo.\n");
