const API_BASE = "https://eduadvisor-production.up.railway.app";
const ADMIN_API_KEY = process.env.ADMIN_API_KEY;
if (!ADMIN_API_KEY) { console.error("❌  Falta ADMIN_API_KEY."); process.exit(1); }

const updates = [
  { id: "cmq15v29s00ddqi3163202uce", name: "CEC EZEIZA", payload: { levels: ["INICIAL","PRIMARIA","SECUNDARIA"], description: "Centro educativo privado de Ezeiza con los niveles inicial, primario y secundario. El CEC Ezeiza ofrece una propuesta integral orientada al desarrollo académico y personal de sus alumnos en el marco de la comunidad aeroportuaria del sur del Gran Buenos Aires. Una institución comprometida con la formación de ciudadanos responsables en la zona de mayor conectividad aérea del país." } },
  { id: "cmq15v27s00crqi31q4ggnm3p", name: "Colegio Jorge Newbery", payload: { levels: ["INICIAL","PRIMARIA","SECUNDARIA"], description: "Institución privada de Ezeiza que lleva el nombre de Jorge Newbery, el Mago del Aire, pionero de la aviación argentina y figura heroica fallecida en 1914. En el partido que alberga el aeropuerto internacional más importante del país, el Colegio Newbery honra el legado del aviador que abrió el cielo argentino. Ofrece los niveles inicial, primario y secundario con una propuesta que celebra el espíritu de la aventura, la superación y la conquista del cielo." } },
  { id: "cmq15v24t00buqi31bnbyx3rz", name: "COLEGIO NUESTRA SEÑORA DE LA SALUD", payload: { levels: ["INICIAL","PRIMARIA","SECUNDARIA"], description: "Institución privada de Ezeiza bajo la advocación de Nuestra Señora de la Salud, imagen mariana que evoca la protección divina sobre el cuerpo y el alma. Ofrece los niveles inicial, primario y secundario con una propuesta que integra la devoción mariana con una formación académica actualizada. Una institución con espiritualidad sanadora comprometida con el bienestar integral de sus alumnos en el partido de Ezeiza." } },
  { id: "cmq15ui9s0098qi31qwepdnrx", name: "Colegio Palabras de Ezeiza", payload: { levels: ["INICIAL","PRIMARIA","SECUNDARIA"], description: "Institución privada de Ezeiza cuyo nombre, Palabras, evoca el lenguaje, la expresión y la comunicación como herramientas esenciales del ser humano y del aprendizaje. Ofrece los niveles inicial, primario y secundario con una propuesta pedagógica que privilegia la lectura, la escritura y la expresión oral como competencias centrales de la formación. Una institución que cultiva el poder de las palabras en el partido que lleva el nombre del aeropuerto internacional más importante de la Argentina." } },
  { id: "cmq15ui6p008bqi315y69xi2z", name: "Colegio privado BEEHIVE ebs en Ezeiza", payload: { levels: ["INICIAL","PRIMARIA","SECUNDARIA"], description: "Institución bilingüe privada de Ezeiza cuyo nombre, Beehive (colmena en inglés), evoca el trabajo colaborativo, la organización y la productividad colectiva como valores del aprendizaje. Ofrece los niveles inicial, primario y secundario con una propuesta bilingüe español-inglés orientada al trabajo en equipo, la creatividad y el desarrollo de competencias globales. Una institución con vocación internacional en el partido que conecta la Argentina con el mundo." } },
  { id: "cmq15v25t00c5qi31eb11i6mg", name: "Colegio San Ignacio", payload: { levels: ["INICIAL","PRIMARIA","SECUNDARIA"], description: "Institución privada de Ezeiza bajo el patronazgo de San Ignacio de Loyola, fundador de la Compañía de Jesús y maestro del discernimiento espiritual. Ofrece los niveles inicial, primario y secundario con la pedagogía ignaciana centrada en la formación del magis —siempre más— y el servicio a los demás a través de la excelencia académica. Una institución con espiritualidad jesuítica comprometida con la formación integral en el partido de Ezeiza." } },
  { id: "cmq15v26s00cgqi31tvjtyd1x", name: "Escuela Hogar \"Evita\"", payload: { levels: ["PRIMARIA","SECUNDARIA"], description: "Institución pública de internado de Ezeiza que lleva el nombre de Eva Perón, la abanderada de los humildes. La Escuela Hogar Evita ofrece los niveles primario y secundario en modalidad de internado para niños y jóvenes en situación de vulnerabilidad social, con alojamiento, alimentación y educación de calidad. Una institución que encarna el legado de Eva Perón en la lucha por la igualdad y el acceso a la educación para todos los argentinos." } },
  { id: "cmq15v28r00d2qi31mw9qqw0a", name: "Instituto Amanecer", payload: { levels: ["INICIAL","PRIMARIA","SECUNDARIA"], description: "Institución privada de Ezeiza cuyo nombre, Amanecer, evoca el comienzo del día y la esperanza de un nuevo comienzo como metáfora del aprendizaje y el crecimiento. Ofrece los niveles inicial, primario y secundario con una propuesta pedagógica que celebra cada nuevo día como una oportunidad de superación. Una institución comprometida con el acompañamiento del desarrollo de sus alumnos en el dinámico partido de Ezeiza." } },
  { id: "cmq15v2at00doqi310nf0i7k3", name: "Instituto Jesús Niño", payload: { levels: ["INICIAL","PRIMARIA","SECUNDARIA"], description: "Institución privada de Ezeiza bajo la advocación de Jesús Niño, imagen de la infancia divina que celebra la sencillez, la ternura y la presencia de Dios en lo cotidiano. Ofrece los niveles inicial, primario y secundario con una propuesta que integra la espiritualidad centrada en la infancia de Jesús con una formación académica de calidad. Una institución con ambiente familiar y arraigo en la comunidad del partido de Ezeiza." } },
  { id: "cmq15v22u00baqi31lz8f3sje", name: "Instituto Técnico Juan Bautista Peña - Ezeiza", payload: { levels: ["SECUNDARIA"], description: "Instituto técnico secundario privado de Ezeiza que lleva el nombre de Juan Bautista Peña, figura vinculada a la historia educativa y política de la Argentina. Ofrece el nivel secundario técnico con orientaciones que responden a las necesidades productivas y de servicios del partido de Ezeiza. Una institución comprometida con la formación de técnicos calificados para el mercado laboral del sur del Gran Buenos Aires." } },
  { id: "cmq15uiar009jqi31a1cwvg50", name: "Santa María del Buen Ayre", payload: { levels: ["INICIAL","PRIMARIA","SECUNDARIA"], description: "Institución privada de Ezeiza bajo la advocación de Santa María del Buen Ayre, la Virgen marinera que dio nombre a la ciudad de Buenos Aires. Ofrece los niveles inicial, primario y secundario con una propuesta que integra la devoción a la patrona histórica de la ciudad con una formación académica de calidad. En el partido que alberga el aeropuerto que conecta Buenos Aires con el mundo, una institución con raíces en la espiritualidad fundacional de la capital argentina." } },
];

async function patchSchool(id, name, payload) {
  const url = `${API_BASE}/v1/schools/id/${id}/profile`;
  const res = await fetch(url, { method: "PATCH", headers: { "content-type": "application/json", "x-admin-key": ADMIN_API_KEY }, body: JSON.stringify(payload) });
  if (res.ok) { console.log(`✅  ${name}`); } else { const body = await res.text(); console.error(`❌  ${name} — HTTP ${res.status}: ${body}`); }
}

console.log(`\n🏫  Curando ${updates.length} colegios de Ezeiza...\n`);
for (const { id, name, payload } of updates) { await patchSchool(id, name, payload); }
console.log("\n✨  Listo.\n");
