const API_BASE = "https://eduadvisor-production.up.railway.app";
const ADMIN_API_KEY = process.env.ADMIN_API_KEY;
if (!ADMIN_API_KEY) { console.error("❌  Falta ADMIN_API_KEY."); process.exit(1); }

const updates = [
  { id: "cmpq2zgs802jxrn5qqiria1w3", name: "Colegio Américo Vespucio", payload: { levels: ["INICIAL","PRIMARIA","SECUNDARIA"], description: "Institución privada de Salta que lleva el nombre del navegante florentino Américo Vespucio, quien dio nombre al continente americano. Ofrece los niveles inicial, primario y secundario con una propuesta que celebra el espíritu explorador y la curiosidad como motores del aprendizaje. En una ciudad colonial y rica en historia como Salta, el colegio forma alumnos con sentido de la aventura y el descubrimiento." } },
  { id: "cmpq2zh0i02otrn5qsf8ok20d", name: "Colegio Belgrano Salta", payload: { levels: ["INICIAL","PRIMARIA","SECUNDARIA"], description: "Institución privada de Salta que lleva el nombre del prócer Manuel Belgrano, creador de la bandera y símbolo de los valores patrióticos. Ofrece los niveles inicial, primario y secundario con una propuesta que reivindica los ideales belgranistas de educación, esfuerzo y amor a la patria. Una institución con identidad histórica arraigada en la hermosa Salta, ciudad colonial del noroeste." } },
  { id: "cmpq2zgxe02mzrn5qiuf3pu35", name: "Colegio de Jesús - Esclavas del Corazón de Jesús", payload: { levels: ["INICIAL","PRIMARIA","SECUNDARIA"], description: "Institución privada de las Esclavas del Corazón de Jesús en Salta, congregación fundada con espiritualidad eucarística y apostólica. Ofrece los niveles inicial, primario y secundario con una propuesta centrada en el amor a Jesús sacramentado y la misión apostólica. Con presencia histórica en el noroeste argentino, es una institución de referencia de la educación católica salteña." } },
  { id: "cmpq2zh7w02t3rn5qvqr59w0a", name: "Colegio de la Divina Misericordia", payload: { levels: ["INICIAL","PRIMARIA","SECUNDARIA"], description: "Institución privada católica de Salta bajo la advocación de la Divina Misericordia, devoción promovida por Santa Faustina Kowalska. Ofrece los niveles inicial, primario y secundario con una espiritualidad centrada en el amor misericordioso de Dios. Una institución con identidad espiritual marcada en la comunidad salteña, formando alumnos con compasión, fe y compromiso con el prójimo." } },
  { id: "cmpq2zgrp02jmrn5qx8i9ofmj", name: "Colegio Italo Argentino Bilingüe Dante Alighieri", payload: { levels: ["INICIAL","PRIMARIA","SECUNDARIA"], description: "Institución bilingüe ítalo-argentina de Salta que lleva el nombre del poeta Dante Alighieri. Ofrece los niveles inicial, primario y secundario con una propuesta bilingüe español-italiano que celebra el vínculo entre Italia y Salta, ciudad que recibió importantes oleadas de inmigrantes italianos. Una institución con identidad transatlántica y compromiso con la excelencia lingüística en el noroeste." } },
  { id: "cmpq2zgsp02k8rn5q0g8pegbg", name: "Colegio José Manuel Estrada", payload: { levels: ["INICIAL","PRIMARIA","SECUNDARIA"], description: "Institución privada de Salta que lleva el nombre del pensador y político católico José Manuel Estrada, figura clave del catolicismo liberal argentino del siglo XIX. Ofrece los niveles inicial, primario y secundario con una propuesta que integra el legado intelectual y cívico de Estrada con una formación de calidad. Una institución con identidad histórica y compromiso con los valores democráticos en Salta." } },
  { id: "cmpq2zh0002oirn5qlr4z099l", name: "Colegio Madre Teresa de Calcuta", payload: { levels: ["INICIAL","PRIMARIA","SECUNDARIA"], description: "Institución privada de Salta que lleva el nombre de la Madre Teresa de Calcuta, Santa canonizada en 2016 y símbolo universal de la caridad y el servicio a los más pobres. Ofrece los niveles inicial, primario y secundario con una propuesta que pone el amor a los más vulnerables como eje de la formación. Una institución que inspira a sus alumnos con el ejemplo de la santa de los descartados." } },
  { id: "cmpq2zgom02hsrn5q1r3y58yu", name: "Colegio Magnus", payload: { levels: ["INICIAL","PRIMARIA","SECUNDARIA"], description: "Institución privada de Salta con los niveles inicial, primario y secundario. Su nombre, Magnus —grande en latín—, refleja una propuesta educativa orientada a la grandeza en todas sus dimensiones: académica, humana y espiritual. El Colegio Magnus forma alumnos que aspiran a dar lo mejor de sí mismos, inspirados por los grandes valores que hacen grande a una persona y a una comunidad." } },
  { id: "cmpq2zh1f02pfrn5q3zjav8h4", name: "Colegio Nuestra Señora del Huerto", payload: { levels: ["INICIAL","PRIMARIA","SECUNDARIA"], description: "Institución privada católica de Salta bajo la advocación de Nuestra Señora del Huerto. Ofrece los niveles inicial, primario y secundario con una propuesta que une la devoción mariana con una educación integral de calidad. En la ciudad colonial de Salta, esta institución cultiva el crecimiento de sus alumnos con la paciencia y el amor que inspira la imagen del huerto como espacio sagrado." } },
  { id: "cmpq2zgq402iprn5qff0m06f8", name: "Colegio Privado San Marcos", payload: { levels: ["INICIAL","PRIMARIA","SECUNDARIA"], description: "Institución privada de Salta bajo el patronazgo de San Marcos Evangelista, autor del segundo evangelio y símbolo de la energía y el dinamismo apostólico. Ofrece los niveles inicial, primario y secundario con una propuesta que integra la fe cristiana con una formación académica actualizada. Con arraigo en la comunidad salteña, forma alumnos con dinamismo, fe y compromiso con su entorno." } },
  { id: "cmpq2zgqn02j0rn5qkcp3ftr7", name: "Colegio Salesiano Angel Zerda", payload: { levels: ["INICIAL","PRIMARIA","SECUNDARIA"], description: "Institución salesiana de Salta que lleva el nombre del Padre Ángel Zerda, salesiano misionero en el noroeste argentino. Ofrece los niveles inicial, primario y secundario con el sistema preventivo de Don Bosco y el carisma misionero propio de la presencia salesiana en el NOA. Una institución que honra la memoria de un misionero que dedicó su vida a la educación y evangelización del noroeste." } },
  { id: "cmpq2zgtq02kurn5q02uj6wn9", name: "Colegio San Agustín", payload: { levels: ["INICIAL","PRIMARIA","SECUNDARIA"], description: "Institución privada agustiniana de Salta bajo el patronazgo de San Agustín de Hipona, Doctor de la Iglesia. Ofrece los niveles inicial, primario y secundario con la tradición agustiniana que privilegia la búsqueda de la verdad y la interioridad. En Salta, ciudad con profunda fe popular, el carisma agustiniano alimenta una propuesta de excelencia intelectual y vida espiritual auténtica." } },
  { id: "cmpq2zgzi02o7rn5q1g5ph4i9", name: "Colegio San José", payload: { levels: ["INICIAL","PRIMARIA","SECUNDARIA"], description: "Institución privada católica de Salta bajo el patronazgo de San José. Ofrece los niveles inicial, primario y secundario con una propuesta que toma a San José como modelo del trabajo honrado, la paternidad y la entrega silenciosa. Con historia en la ciudad, es una de las referencias de la educación católica salteña valorada por las familias por su clima cálido y su excelencia académica." } },
  { id: "cmpq2zh1x02pqrn5qwo0mcvb2", name: "Colegio San Pablo", payload: { levels: ["INICIAL","PRIMARIA","SECUNDARIA"], description: "Institución privada de Salta bajo el patronazgo del apóstol San Pablo. Ofrece los niveles inicial, primario y secundario con una espiritualidad paulina orientada al anuncio, la apertura al mundo y la transformación personal por el encuentro con Cristo. Una institución que forma alumnos con convicción y coraje para vivir y transmitir sus valores en la hermosa Salta." } },
  { id: "cmpq2zh9102tnrn5q4uza92c2", name: "Colegio San Rafael Arcángel", payload: { levels: ["INICIAL","PRIMARIA","SECUNDARIA"], description: "Institución privada de Salta bajo el patronazgo del Arcángel San Rafael, patrono de los viajeros, los médicos y los enamorados. Ofrece los niveles inicial, primario y secundario con una propuesta que integra la espiritualidad angélica con una formación académica actualizada. Una institución que forma alumnos con sanación interior, acompañamiento y apertura al camino de la vida." } },
  { id: "cmpq2zh2d02q1rn5qvhq3fc8a", name: "Colegio Santa Isabel de Hungría", payload: { levels: ["INICIAL","PRIMARIA","SECUNDARIA"], description: "Institución privada de Salta bajo el patronazgo de Santa Isabel de Hungría, reina medieval que renunció al lujo para servir a los pobres. Ofrece los niveles inicial, primario y secundario con una espiritualidad franciscana de servicio y caridad. Una institución que inspira a sus alumnos con el ejemplo de una santa que eligió los pobres sobre la corona en el corazón del noroeste argentino." } },
  { id: "cmpq2zgt802kjrn5qjzafgfyy", name: "Colegio Santa María", payload: { levels: ["INICIAL","PRIMARIA","SECUNDARIA"], description: "Institución privada católica de Salta bajo la advocación de Santa María. Ofrece los niveles inicial, primario y secundario con una propuesta que integra la devoción mariana con una formación académica actualizada. Con arraigo en la comunidad salteña, es una institución valorada por su clima espiritual y el acompañamiento personalizado a las familias de una de las ciudades más devotas de la Argentina." } },
  { id: "cmpq2zh4c02qyrn5q7v0lnc63", name: "Colegio Santa Rosa de Viterbo", payload: { levels: ["INICIAL","PRIMARIA","SECUNDARIA"], description: "Institución privada de Salta bajo el patronazgo de Santa Rosa de Viterbo, joven terciaria franciscana italiana del siglo XIII, modelo de entrega y fe juvenil. Ofrece los niveles inicial, primario y secundario con la espiritualidad franciscana y el ejemplo de una joven santa que vivió el evangelio con radicalidad. Una institución que forma alumnos con juventud creyente y compromiso social en el NOA." } },
  { id: "cmpq2zgve02lrrn5qpw4o4f8l", name: "Colegio Santa Teresa de Jesús", payload: { levels: ["INICIAL","PRIMARIA","SECUNDARIA"], description: "Institución privada carmelita de Salta bajo el patronazgo de Santa Teresa de Jesús, Doctora de la Iglesia. Ofrece los niveles inicial, primario y secundario con la espiritualidad teresiana centrada en la oración y la interioridad. En Salta, ciudad de intensa vida religiosa y devocional, el carisma carmelita nutre una propuesta de profundidad espiritual y solidez académica." } },
  { id: "cmpq2zgub02l5rn5qsp2nnpee", name: "Colegio Santo Tomás de Aquino", payload: { levels: ["INICIAL","PRIMARIA","SECUNDARIA"], description: "Institución privada de Salta bajo el patronazgo de Santo Tomás de Aquino, el Doctor Angélico. Ofrece los niveles inicial, primario y secundario con la tradición intelectual tomista que une fe y razón en la búsqueda de la verdad. Una institución que forma alumnos con rigor intelectual, apertura filosófica y vocación por el conocimiento en la ciudad colonial del noroeste argentino." } },
  { id: "cmpq2zgp302i3rn5qi4hf9ysu", name: "Colegio Santo Tomás de Villanueva", payload: { levels: ["INICIAL","PRIMARIA","SECUNDARIA"], description: "Institución privada agustiniana de Salta bajo el patronazgo de Santo Tomás de Villanueva, arzobispo agustino del siglo XVI conocido como el limosnero por su generosidad extrema con los pobres. Ofrece los niveles inicial, primario y secundario con la espiritualidad agustiniana y el carisma de la generosidad. Una institución que forma alumnos con amor a la verdad y apertura solidaria." } },
  { id: "cmpq2zh7b02ssrn5qbbvlzq3b", name: "Colegio Superior San Pedro", payload: { levels: ["INICIAL","PRIMARIA","SECUNDARIA","SUPERIOR"], description: "Institución privada de Salta bajo el patronazgo de San Pedro Apóstol, con los niveles inicial, primario, secundario y superior. Su trayectoria educativa completa la convierte en una de las pocas instituciones del noroeste que ofrece desde el jardín hasta el terciario bajo el mismo techo institucional. Una referencia de la continuidad educativa en Salta para las familias que buscan acompañamiento integral." } },
  { id: "cmpq2zgwe02mdrn5qg6lckf1i", name: "Colegio Verbum", payload: { levels: ["INICIAL","PRIMARIA","SECUNDARIA"], description: "Institución privada de Salta cuyo nombre, Verbum —Palabra en latín—, evoca el Evangelio de Juan: 'En el principio era el Verbo'. Ofrece los niveles inicial, primario y secundario con una propuesta que pone la palabra —escrita, oral, sagrada— como eje del aprendizaje y la comunicación. Una institución que forma alumnos con amor a la lengua, la literatura y el diálogo en el noroeste argentino." } },
  { id: "cmpq2zgxx02narn5qekmw85nd", name: "Dirección General de Educación Privada", payload: { levels: ["INICIAL","PRIMARIA","SECUNDARIA"], description: "Institución educativa privada de Salta con los niveles inicial, primario y secundario. Ofrece una propuesta educativa integral orientada al desarrollo académico y personal de sus alumnos en la capital salteña. Con compromiso docente y arraigo en la comunidad, forma ciudadanos preparados para los desafíos de la vida universitaria y profesional en el noroeste argentino." } },
  { id: "cmpq2zh3t02qnrn5qxv5he5aa", name: "Enseñanza Particular Salta", payload: { levels: ["INICIAL","PRIMARIA","SECUNDARIA"], description: "Institución privada de Salta con los niveles inicial, primario y secundario. Enseñanza Particular Salta ofrece una propuesta educativa con arraigo en la comunidad salteña, comprometida con la calidad académica y el acompañamiento personalizado de cada alumno en una de las ciudades más hermosas y culturalmente ricas del noroeste argentino." } },
  { id: "cmpq2zh6t02shrn5q9t3z4fni", name: "Escuela de Educación Técnica República de la India", payload: { levels: ["SECUNDARIA"], description: "Institución de educación secundaria técnica de Salta que lleva el nombre de la República de la India, en honor al vínculo cultural y diplomático entre los dos países. Ofrece formación técnica especializada que prepara a los egresados para el mercado laboral y el ingreso universitario. Su perfil técnico responde a las necesidades productivas del noroeste argentino." } },
  { id: "cmpq2zgwy02morn5qp9bcpxsr", name: "Escuela del Cerro", payload: { levels: ["INICIAL","PRIMARIA","SECUNDARIA"], description: "Institución privada de Salta cuyo nombre evoca los cerros que enmarcan la ciudad, símbolo del paisaje y la identidad salteña. Ofrece los niveles inicial, primario y secundario con una propuesta que celebra la geografía y la cultura del noroeste. En una ciudad rodeada de cerros que inspiran respeto y belleza, la Escuela del Cerro forma alumnos con arraigo territorial y amor por la Salta profunda." } },
  { id: "cmpq2zh4s02r9rn5qogoiia0q", name: "Escuela Parroquial Nuestra Señora de la Merced", payload: { levels: ["INICIAL","PRIMARIA","SECUNDARIA"], description: "Institución parroquial de Salta bajo la advocación de Nuestra Señora de la Merced, patrona de Córdoba y venerada en toda Argentina. Ofrece los niveles inicial, primario y secundario con la espiritualidad mercedaria orientada a la liberación y el servicio. Con arraigo en la vida parroquial salteña, es una institución comprometida con las familias de la comunidad y la formación integral." } },
  { id: "cmpq2zh3d02qcrn5q04klncm6", name: "Instituto Bicentenario María Reina", payload: { levels: ["INICIAL","PRIMARIA","SECUNDARIA"], description: "Institución privada de Salta fundada en el marco del Bicentenario de la Argentina bajo la advocación de María Reina. Ofrece los niveles inicial, primario y secundario con una propuesta que celebra la identidad nacional argentina y la devoción mariana en el contexto del bicentenario patrio. Una institución con identidad histórica y espiritual arraigada en la comunidad salteña." } },
  { id: "cmpq2zh5r02rvrn5q2uh94h2g", name: "Instituto Carlos Guido Spano", payload: { levels: ["INICIAL","PRIMARIA","SECUNDARIA"], description: "Institución privada de Salta que lleva el nombre del poeta y político argentino Carlos Guido Spano, autor del célebre poema Nenia y figura de la literatura romántica argentina del siglo XIX. Ofrece los niveles inicial, primario y secundario con una propuesta que privilegia la literatura y las humanidades. Una institución con alma poética en el corazón del noroeste argentino." } },
  { id: "cmpq2zh0y02p4rn5ql12ut72y", name: "Instituto de Educación Integral de Salta", payload: { levels: ["INICIAL","PRIMARIA","SECUNDARIA"], description: "Institución privada de Salta con los niveles inicial, primario y secundario. El Instituto de Educación Integral vive fiel a su nombre desarrollando todas las dimensiones del alumno: académica, artística, deportiva y social. Una institución comprometida con la formación completa de cada estudiante en la capital de la provincia más hermosa del noroeste argentino." } },
  { id: "cmpq2zgvx02m2rn5qe014rtjt", name: "Instituto Dr. Bernardo Frías", payload: { levels: ["INICIAL","PRIMARIA","SECUNDARIA"], description: "Institución privada de Salta que lleva el nombre del historiador y escritor salteño Bernardo Frías, autor de la monumental Historia del General Güemes y la provincia de Salta. Ofrece los niveles inicial, primario y secundario con una propuesta que reivindica el conocimiento de la historia y la cultura del noroeste. Una institución que honra a quien mejor contó la historia de la heroica Salta." } },
  { id: "cmpq2zh6702s6rn5qkvymzom9", name: "Instituto Educativo INTI", payload: { levels: ["INICIAL","PRIMARIA","SECUNDARIA"], description: "Institución privada de Salta cuyo nombre, INTI, es la palabra quechua para el sol, divinidad central de la cosmovisión andina. Ofrece los niveles inicial, primario y secundario con una propuesta que celebra la identidad cultural andina y la cosmovisión de los pueblos originarios del noroeste. Una institución que forma alumnos con respeto por la diversidad cultural y arraigo en la tierra del sol." } },
  { id: "cmpq2zgpj02iern5qmb69xndi", name: "Instituto María del Rosario de San Nicolás", payload: { levels: ["INICIAL","PRIMARIA","SECUNDARIA"], description: "Institución privada de Salta bajo la advocación de María del Rosario de San Nicolás, Virgen aparecida en San Nicolás de los Arroyos. Ofrece los niveles inicial, primario y secundario con una propuesta que integra la devoción a esta Virgen argentina con una formación académica actualizada. Una institución con espiritualidad mariana nacional en el devoto noroeste argentino." } },
  { id: "cmpq2zh5902rkrn5q7lvdo1k9", name: "Instituto Pablo Neruda", payload: { levels: ["INICIAL","PRIMARIA","SECUNDARIA"], description: "Institución privada de Salta que lleva el nombre del poeta chileno Pablo Neruda, Premio Nobel de Literatura 1971 y uno de los poetas más importantes del idioma español. Ofrece los niveles inicial, primario y secundario con una propuesta que privilegia la poesía, la literatura y la expresión creativa como dimensiones esenciales de la educación. Una institución con alma poética en el noroeste argentino." } },
  { id: "cmpq2zgz002nwrn5q0nsupk0n", name: "Instituto Perito Moreno", payload: { levels: ["INICIAL","PRIMARIA","SECUNDARIA"], description: "Institución privada de Salta que lleva el nombre del explorador y geógrafo Francisco Pascasio Moreno, el Perito Moreno, quien recorrió la Patagonia y delimitó las fronteras argentinas. Ofrece los niveles inicial, primario y secundario con una propuesta que celebra el espíritu explorador y el amor por la geografía argentina. Una institución que inspira a descubrir y cuidar la tierra argentina." } },
  { id: "cmpq2zgr402jbrn5qbvy9pt4b", name: "Instituto Privado General Güemes", payload: { levels: ["INICIAL","PRIMARIA","SECUNDARIA"], description: "Institución privada de Salta que lleva el nombre del Héroe Nacional Martín Miguel de Güemes, defensor de la frontera norte de la patria e ídolo salteño. Ofrece los niveles inicial, primario y secundario con una propuesta que reivindica el coraje, el sacrificio y el amor a la patria de quien defendió el noroeste con su vida. Una institución con identidad gaucha y patriótica en la tierra de Güemes." } },
  { id: "cmpq2zgyi02nlrn5qa3rk9d8i", name: "Ludere College", payload: { levels: ["INICIAL","PRIMARIA","SECUNDARIA"], description: "Institución bilingüe privada de Salta cuyo nombre, Ludere —jugar en latín—, refleja una pedagogía que celebra el juego como herramienta fundamental del aprendizaje. Ofrece los niveles inicial, primario y secundario con una propuesta lúdica y bilingüe orientada al desarrollo integral. En la colorida Salta, Ludere College forma alumnos que aprenden jugando y descubriendo el mundo con alegría." } },
  { id: "cmpq2zguu02lgrn5qe7a4jbpx", name: "San Isidro College", payload: { levels: ["INICIAL","PRIMARIA","SECUNDARIA"], description: "Instituto bilingüe privado de Salta con los niveles inicial, primario y secundario. San Isidro College ofrece una propuesta de educación en inglés con estándares internacionales, formando alumnos bilingües con competencias globales en el corazón del noroeste argentino. Una institución de referencia en bilingüismo en Salta para familias que valoran la proyección internacional de sus hijos." } }
];

async function patchSchool(id, name, payload) {
  const url = `${API_BASE}/v1/schools/id/${id}/profile`;
  const res = await fetch(url, { method: "PATCH", headers: { "content-type": "application/json", "x-admin-key": ADMIN_API_KEY }, body: JSON.stringify(payload) });
  if (res.ok) { console.log(`✅  ${name}`); } else { const body = await res.text(); console.error(`❌  ${name} — HTTP ${res.status}: ${body}`); }
}
console.log(`\n🏫  Curando ${updates.length} colegios de Salta...\n`);
for (const { id, name, payload } of updates) { await patchSchool(id, name, payload); }
console.log("\n✨  Listo.\n");
