const API_BASE = "https://eduadvisor-production.up.railway.app";
const ADMIN_API_KEY = process.env.ADMIN_API_KEY;
if (!ADMIN_API_KEY) { console.error("❌  Falta ADMIN_API_KEY."); process.exit(1); }

const updates = [
  { id: "cmpq2vika018trn5qnw5qj6wp", name: "Colegio Bilingüe Los Olivos", payload: { levels: ["INICIAL","PRIMARIA","SECUNDARIA"], description: "Institución bilingüe privada de Maipú cuyo nombre, Los Olivos, evoca los olivares que junto a las vides definen el paisaje agrícola de este departamento mendocino. Ofrece los niveles inicial, primario y secundario con una propuesta bilingüe español-inglés que forma alumnos con competencias globales y arraigo en la identidad productiva y cultural de Maipú, la capital del vino de Mendoza." } },
  { id: "cmq2kzd4z003islmymjemy2qh", name: "Colegio DelPilar", payload: { levels: ["INICIAL","PRIMARIA","SECUNDARIA"], description: "Institución privada de Maipú con los niveles inicial, primario y secundario. El Colegio Del Pilar lleva implícita la advocación a la Virgen del Pilar, patrona de la hispanidad. Una institución con arraigo en la comunidad del departamento mendocino más reconocido por su producción vitivinícola, comprometida con la formación integral de sus alumnos en un entorno de viñedos y tradición cuyana." } },
  { id: "cmq2kzd3y002wslmy5c0zez6w", name: "Colegio Del Pilar kinder", payload: { levels: ["INICIAL"], description: "Jardín de infantes del Colegio Del Pilar de Maipú, dedicado a los primeros años de escolaridad en un entorno cálido y estimulante. Ofrece el nivel inicial con una propuesta pedagógica centrada en el juego, la exploración y el vínculo afectivo como cimientos del aprendizaje. El primer paso de un proyecto educativo arraigado en la identidad del departamento vitivinícola más importante de Mendoza." } },
  { id: "cmq2kzd2x002aslmyihp16qlg", name: "Colegio Divina Trinidad / Jardín Mio Piccolo Amore", payload: { levels: ["INICIAL","PRIMARIA","SECUNDARIA"], description: "Institución privada de Maipú bajo la advocación de la Divina Trinidad, con jardín de infantes bajo el nombre italiano Mio Piccolo Amore —Mi Pequeño Amor—, evocando la herencia italiana tan presente en la cultura mendocina. Ofrece los niveles inicial, primario y secundario con una propuesta que integra la espiritualidad trinitaria con la calidez y el amor como fundamentos de la educación en el corazón de la región del vino." } },
  { id: "cmq2kzd4h0037slmyc5nedser", name: "Colegio La Huella", payload: { levels: ["INICIAL","PRIMARIA","SECUNDARIA"], description: "Institución privada de Maipú cuyo nombre, La Huella, evoca el camino, el rastro y la identidad que cada persona deja en el mundo como fruto de su formación. Ofrece los niveles inicial, primario y secundario con una propuesta pedagógica que busca que cada alumno deje su propia huella positiva en la comunidad. Una institución que forma ciudadanos con identidad sólida, valores claros y vocación de impacto en el departamento vitivinícola de Mendoza." } },
  { id: "cmq2kzd1j001oslmyvvnysil5", name: "Colegio León XIII - Jardín", payload: { levels: ["INICIAL"], description: "Jardín de infantes del Colegio León XIII de Maipú, que lleva el nombre del Papa León XIII, autor de la encíclica Rerum Novarum y padre de la doctrina social de la Iglesia Católica. Ofrece el nivel inicial con la espiritualidad leonina centrada en la justicia social y la dignidad humana. El primer eslabón de un proyecto educativo católico comprometido con la formación integral desde los primeros años en el departamento mendocino del vino." } },
  { id: "cmq2kzd5h003tslmybns9opsj", name: "Colegio León XIII - Primaria", payload: { levels: ["PRIMARIA"], description: "Sede primaria del Colegio León XIII de Maipú, que lleva el nombre del Papa León XIII y su legado de doctrina social centrada en la justicia y el trabajo. Ofrece el nivel primario con una propuesta que integra los valores de la encíclica Rerum Novarum —dignidad del trabajador, bien común y solidaridad— con una formación académica de calidad en el corazón del departamento vitivinícola de Mendoza." } },
  { id: "cmq2kzd96005wslmy42nedskt", name: "Colegio María Auxiliadora, Rodeo del Medio, Mendoza", payload: { levels: ["INICIAL","PRIMARIA","SECUNDARIA"], description: "Institución salesiana de Rodeo del Medio, en el departamento de Maipú, dirigida por las Hijas de María Auxiliadora. Ofrece los niveles inicial, primario y secundario con la espiritualidad de Don Bosco y la devoción mariana como ejes formativos. Con presencia salesiana arraigada en la comunidad rural del este mendocino, forma alumnos con sólida preparación académica, fe viva y amor por la tierra y la identidad cuyana." } },
  { id: "cmq2kzd3e002lslmy3358piof", name: "COLEGIO SAN FRANCISCO JAVIER", payload: { levels: ["INICIAL","PRIMARIA","SECUNDARIA"], description: "Institución privada de Maipú bajo el patronazgo de San Francisco Javier, jesuita español que evangelizó Asia y es patrono de las misiones. Ofrece los niveles inicial, primario y secundario con la pedagogía ignaciana centrada en el magis —siempre más— y la búsqueda de la excelencia al servicio de los demás. Una institución con espiritualidad misionera y compromiso con la formación integral en el departamento del vino de Mendoza." } },
  { id: "cmq2kzd600044slmyceluor8x", name: "Colegio San Jorge, Maipu (K4, K5) Primaria 2025", payload: { levels: ["INICIAL","PRIMARIA"], description: "Institución privada de Maipú bajo el patronazgo de San Jorge, caballero mártir y símbolo del valor y la protección. Ofrece los niveles inicial (K4, K5) y primario con una propuesta pedagógica que integra la valentía, el servicio y la formación académica sólida desde los primeros años. Una institución en crecimiento que acompaña a sus alumnos desde la primera infancia en el corazón del departamento vitivinícola mendocino." } },
  { id: "cmq2kzd2f001zslmylycy9mpp", name: "Colegio Santa Clara", payload: { levels: ["INICIAL","PRIMARIA","SECUNDARIA"], description: "Institución privada de Maipú bajo el patronazgo de Santa Clara de Asís, fundadora de las Clarisas y primera mujer que redactó una regla religiosa aprobada por la Iglesia. Ofrece los niveles inicial, primario y secundario con la espiritualidad franciscana de pobreza evangélica, alegría y contemplación. Una institución que honra el legado de Clara en la hermosa región de viñedos y montañas de Mendoza." } },
  { id: "cmq2kzd030012slmyrr5yzs69", name: "Colegio Virgen del Carmen de Cuyo", payload: { levels: ["INICIAL","PRIMARIA","SECUNDARIA"], description: "Institución privada de Maipú bajo la advocación de la Virgen del Carmen de Cuyo, patrona de las armas y bendecida por San Martín antes de cruzar los Andes en 1817. Ofrece los niveles inicial, primario y secundario con una propuesta que integra la devoción carmelita y la memoria sanmartiniana con una formación académica de calidad. Una institución con raíces profundas en la identidad histórica y espiritual de la región de Cuyo." } },
  { id: "cmq2kzczm000rslmyhaccg7hg", name: "Colegio Vitivinícola", payload: { levels: ["SECUNDARIA","SUPERIOR"], description: "Institución única en su tipo en Maipú, departamento declarado capital vitivinícola de Mendoza y epicentro de la industria del vino en Argentina. El Colegio Vitivinícola ofrece una formación especializada en viticultura, enología y agroindustria orientada al mercado laboral de la región. Una institución que prepara a sus egresados para integrarse a las bodegas, fincas y empresas del sector vitivinícola más importante del país." } },
  { id: "cmq2kzd8o005lslmyziv4kha6", name: "Escuela Aguaribay", payload: { levels: ["INICIAL","PRIMARIA","SECUNDARIA"], description: "Institución privada de Maipú cuyo nombre, Aguaribay, lleva el nombre del árbol nativo argentino también llamado pimiento o molle, presente en los paisajes rurales de Mendoza y símbolo del arraigo en la tierra. Ofrece los niveles inicial, primario y secundario con una propuesta que celebra la naturaleza, la identidad regional y el vínculo con el entorno como ejes de la formación en el departamento vitivinícola mendocino." } },
  { id: "cmq2kzd7g0051slmy1aktqaed", name: "Escuela Lisandro AGUIRRE", payload: { levels: ["INICIAL","PRIMARIA","SECUNDARIA"], description: "Institución privada de Maipú que lleva el nombre de Lisandro Aguirre, figura vinculada a la historia educativa y cívica de la región cuyana. Ofrece los niveles inicial, primario y secundario con una propuesta que honra su memoria a través de una educación comprometida con la calidad académica y la formación ciudadana. Una institución con arraigo en la comunidad mendocina del departamento del vino." } },
  { id: "cmpq2vio301ayrn5q1yprt4l1", name: "IMEI - Instituto Maipú de Educación Integral", payload: { levels: ["INICIAL","PRIMARIA","SECUNDARIA"], description: "Institución privada de Maipú que lleva con orgullo el nombre del departamento mendocino en su propuesta de educación integral. El IMEI ofrece los niveles inicial, primario y secundario con una propuesta que busca el desarrollo pleno de cada alumno en sus dimensiones intelectual, afectiva, social y creativa. Una institución comprometida con la excelencia educativa en la capital vitivinícola de Mendoza." } },
  { id: "cmq2kzd6h004fslmyotttz4v5", name: "Instituto Da Vinci", payload: { levels: ["INICIAL","PRIMARIA","SECUNDARIA"], description: "Institución privada de Maipú que lleva el nombre de Leonardo da Vinci, el genio renacentista que encarnó como ninguno la unidad entre arte, ciencia y técnica. Ofrece los niveles inicial, primario y secundario con una propuesta que fomenta la creatividad, el pensamiento interdisciplinario y la curiosidad como motores del aprendizaje. Una institución que inspira a sus alumnos a ser leonardos contemporáneos en el corazón de la región vitivinícola de Mendoza." } },
  { id: "cmq2kzd12001dslmy3kzmrkox", name: "Instituto Educativo Brook", payload: { levels: ["INICIAL","PRIMARIA","SECUNDARIA"], description: "Institución privada de Maipú con los niveles inicial, primario y secundario. El Instituto Brook ofrece una propuesta educativa integral con arraigo en la comunidad del departamento mendocino. Con un equipo docente comprometido y un clima institucional cálido, forma alumnos con sólida preparación académica y los valores necesarios para desenvolverse en el mundo contemporáneo en el corazón de la región del vino." } },
  { id: "cmq2kzczm000rslmyhaccg7hg", name: "Instituto Padre Vasquez", payload: { levels: ["INICIAL","PRIMARIA","SECUNDARIA"], description: "Institución privada de Maipú que lleva el nombre del Padre Vásquez, figura sacerdotal vinculada a la historia educativa y pastoral de la región cuyana. Ofrece los niveles inicial, primario y secundario con una propuesta que integra la espiritualidad cristiana con una formación académica de calidad. Una institución con identidad sacerdotal y compromiso con el desarrollo integral de sus alumnos en el departamento vitivinícola de Mendoza." } },
  { id: "cmq2kzd6z004qslmyxof12zq0", name: "MARIA CREMASCHI DE CAVAGNARO", payload: { levels: ["INICIAL","PRIMARIA","SECUNDARIA"], description: "Institución privada de Maipú que lleva el nombre de María Cremaschi de Cavagnaro, educadora mendocina que dedicó su vida a la enseñanza y dejó su huella en la comunidad del departamento. Ofrece los niveles inicial, primario y secundario con una propuesta que honra su memoria a través del compromiso con la calidad educativa y la vocación docente. Una institución que mantiene vivo el legado de la maestra en el corazón del departamento vitivinícola mendocino." } },
];

async function patchSchool(id, name, payload) {
  const url = `${API_BASE}/v1/schools/id/${id}/profile`;
  const res = await fetch(url, { method: "PATCH", headers: { "content-type": "application/json", "x-admin-key": ADMIN_API_KEY }, body: JSON.stringify(payload) });
  if (res.ok) { console.log(`✅  ${name}`); } else { const body = await res.text(); console.error(`❌  ${name} — HTTP ${res.status}: ${body}`); }
}

console.log(`\n🏫  Curando ${updates.length} colegios de Maipú...\n`);
for (const { id, name, payload } of updates) { await patchSchool(id, name, payload); }
console.log("\n✨  Listo.\n");
