const API_BASE = "https://eduadvisor-production.up.railway.app";
const ADMIN_API_KEY = process.env.ADMIN_API_KEY;
if (!ADMIN_API_KEY) { console.error("❌  Falta ADMIN_API_KEY."); process.exit(1); }

const updates = [
  { id: "cmq6zbuqj00s312emagltpqi3", name: "Colegio Don Bosco", payload: { levels: ["INICIAL", "PRIMARIA", "SECUNDARIA"], description: "Institución salesiana de Paraná, capital de Entre Ríos, que aplica el sistema preventivo de Don Bosco —razón, religión y amor— en los tres niveles educativos. Con la histórica presencia salesiana en el litoral argentino y décadas de arraigo en la ciudad, es una de las instituciones más reconocidas de la capital entrerriana. Los Salesianos llegaron al litoral argentino con vocación de educación popular y esta institución mantiene vivo ese espíritu." } },
  { id: "cmq6zbupi00rs12ema905pdb0", name: "Colegio El Buen Pastor", payload: { levels: ["INICIAL", "PRIMARIA", "SECUNDARIA"], description: "Institución parroquial de Paraná bajo el carisma del Buen Pastor, imagen evangélica de Cristo que busca a la oveja perdida y cuida al rebaño. Ofrece los tres niveles con formación católica y vínculo estrecho con la comunidad parroquial de la capital entrerriana. Con arraigo en el barrio y compromiso con las familias, es una institución de cercanía que forma alumnos con fe y valores en la capital de Entre Ríos." } },
  { id: "cmq6zbv1c00uj12emz5mxl1m6", name: "Colegio El Madero", payload: { levels: ["INICIAL", "PRIMARIA", "SECUNDARIA"], description: "Institución privada laica de Paraná con los tres niveles y propuesta educativa moderna para las familias de la capital entrerriana. Con énfasis en la calidad académica y el desarrollo integral, ofrece proyecto de inglés y actividades extracurriculares en una ciudad universitaria con altas expectativas educativas. Una opción laica reconocida en el sistema educativo privado paranaense." } },
  { id: "cmq6zbv3l00v512emkr7i8tzp", name: "Colegio Hermanas Mercedarias", payload: { levels: ["INICIAL", "PRIMARIA", "SECUNDARIA"], description: "Institución privada de las Religiosas Mercedarias en Paraná, capital de Entre Ríos. La Orden de la Merced —fundada en 1218 para la redención de cautivos— tiene en las Hermanas Mercedarias a su rama femenina dedicada a la educación. Con los tres niveles y la espiritualidad mercedaria de misericordia y liberación, forma alumnas con fe, conocimiento y compromiso social en la capital entrerriana." } },
  { id: "cmq6zbukd00q912embivh10jb", name: "Colegio La Salle Paraná", payload: { levels: ["INICIAL", "PRIMARIA", "SECUNDARIA"], description: "Institución lasallana de Paraná fundada por los Hermanos de las Escuelas Cristianas, la congregación creada por San Juan Bautista de La Salle en el siglo XVII para dar educación gratuita a los pobres. En la capital de Entre Ríos, aplica la pedagogía lasallana —orientada al servicio y la excelencia— en los tres niveles. Con comunidad sólida y décadas de historia, es una de las referencias de la educación privada paranaense." } },
  { id: "cmq6zbunh00r612emgth7ar45", name: "Colegio Nuestra Señora Del Huerto", payload: { levels: ["INICIAL", "PRIMARIA", "SECUNDARIA"], description: "Institución privada de Paraná bajo la advocación de Nuestra Señora del Huerto, vinculada a la congregación de las Ursulinas fundada por Santa Ángela de Mérici en 1535. Con los tres niveles y formación católica de profunda raíz humanista, es una de las instituciones femeninas más tradicionales de la capital entrerriana. Con décadas de historia y comunidad consolidada, forma alumnas con fe, saber y sensibilidad cultural." } },
  { id: "cmq6zbv0c00u812emtbfje4um", name: "Colegio Privado Nuestra Señora de Luján", payload: { levels: ["INICIAL", "PRIMARIA", "SECUNDARIA"], description: "Institución privada católica de Paraná bajo la advocación de la Virgen de Luján, patrona de Argentina. Con los tres niveles y formación en los valores de la fe nacional, honra la devoción mariana más arraigada del pueblo argentino. En la capital entrerriana, esta institución integra la identidad católica y el amor a la patria con una propuesta académica comprometida con la formación integral de sus alumnos." } },
  { id: "cmq6zbuhg00pc12emwsvjd8j8", name: "Colegio Privado Martín Lutero", payload: { levels: ["INICIAL", "PRIMARIA", "SECUNDARIA"], description: "Institución privada protestante de Paraná que lleva el nombre del reformador alemán Martín Lutero, fundador del protestantismo en el siglo XVI. Con los tres niveles y la tradición protestante de valoración de la Biblia, la conciencia individual y la educación laica, es parte de la diversidad religiosa del litoral argentino. Una institución con identidad reformada y compromiso con la formación integral en la capital de Entre Ríos." } },
  { id: "cmq6zbuvm00t012empyrplykd", name: "Escuela Privada N° 124 Ntra. Sra. de la Esperanza", payload: { levels: ["PRIMARIA", "SECUNDARIA"], description: "Escuela privada de Paraná bajo la advocación de Nuestra Señora de la Esperanza, símbolo de confianza en el futuro y sostén en los momentos difíciles. Ofrece los niveles primario y secundario con formación católica y propuesta pedagógica orientada a la comunidad paranaense. Con arraigo en el barrio y compromiso con las familias, forma alumnos con esperanza y preparación para el mundo en la capital de Entre Ríos." } },
  { id: "cmq6zbuz800tx12emjwypjet2", name: "Escuela Privada N° 5 Virgen de la Medalla Milagrosa", payload: { levels: ["PRIMARIA", "SECUNDARIA"], description: "Escuela privada de Paraná bajo la advocación de la Virgen de la Medalla Milagrosa, cuya aparición a Santa Catalina Labouré en París en 1830 generó una de las devociones marianas más difundidas del mundo. Ofrece los niveles primario y secundario con formación católica y devoción mariana en la capital entrerriana, siendo parte del tejido educativo y espiritual de la comunidad paranaense." } },
  { id: "cmq6zbuof00rh12em6y7n2k1x", name: "Escuela Privada Santa Lucía", payload: { levels: ["PRIMARIA", "SECUNDARIA"], description: "Escuela privada de Paraná bajo el patronazgo de Santa Lucía, mártir siracusana del siglo IV patrona de los ciegos y de los que buscan la luz. Ofrece los niveles primario y secundario con formación católica y propuesta educativa que busca iluminar el camino de sus alumnos en la capital entrerriana. Una institución con identidad espiritual y compromiso con la formación de jóvenes paranaenses." } },
  { id: "cmq6zbule00qk12emo7yrgti8", name: "Escuela Privada Santa Teresita", payload: { levels: ["PRIMARIA", "SECUNDARIA"], description: "Escuela privada de Paraná bajo el patronazgo de Santa Teresita del Niño Jesús, la 'Pequeña Flor' carmelita doctora de la Iglesia. Con su 'pequeño camino' de amor cotidiano y sencillez como ideal espiritual, esta institución ofrece los niveles primario y secundario con calidez y formación en valores en la capital de Entre Ríos. Una comunidad educativa inspirada en la espiritualidad teresiana del amor en las cosas pequeñas." } },
  { id: "cmq6zbuif00pn12emkkx5fl6k", name: "Colegio Plaza Mayor", payload: { levels: ["INICIAL", "PRIMARIA", "SECUNDARIA"], description: "Institución privada laica de la Fundación del Paraná en la capital entrerriana, con los tres niveles y propuesta académica de alto nivel orientada a familias que priorizan la excelencia. Con comunidad activa, docentes especializados y proyecto de inglés, es una de las opciones laicas más reconocidas de Paraná. La Fundación del Paraná impulsa el desarrollo educativo de la ciudad como motor de progreso social y económico de Entre Ríos." } },
  { id: "cmq6zbuy200tm12emflffpwau", name: "Instituto de Enseñanza EDU-PRO", payload: { levels: ["INICIAL", "PRIMARIA", "SECUNDARIA"], description: "Instituto educativo privado de Paraná con propuesta actualizada y orientación profesional para los tres niveles. Con énfasis en la preparación para el mundo laboral y universitario, combina formación académica con habilidades prácticas. Una opción laica y moderna en la capital entrerriana para familias que buscan propuesta educativa con visión de futuro en la ciudad universitaria sobre el Paraná." } },
  { id: "cmq6zbuje00py12em49zh2ooj", name: "Instituto Modelo Bilingüe Michelangelo", payload: { levels: ["INICIAL", "PRIMARIA", "SECUNDARIA"], description: "Instituto bilingüe privado de Paraná que lleva el nombre del genio renacentista Miguel Ángel, símbolo de la creatividad y la excelencia artística. Con propuesta de inmersión en inglés y énfasis en las artes, ofrece los tres niveles para familias de la capital entrerriana que priorizan el bilingüismo real y la formación integral con sensibilidad cultural." } },
  { id: "cmq6zbux000tb12emae9xkl9c", name: "Instituto Santa Ana D-90", payload: { levels: ["INICIAL", "PRIMARIA", "SECUNDARIA"], description: "Instituto privado de Paraná bajo el patronazgo de Santa Ana, madre de la Virgen María y abuela de Jesucristo, patrona de las madres y los abuelos. Con los tres niveles y formación católica centrada en los valores familiares, esta institución paranaense honra el vínculo intergeneracional y el rol de la familia en la educación. Una comunidad educativa con arraigo en la capital de Entre Ríos." } },
  { id: "cmq6zburi00se12em2advlssf", name: "Instituto Siglo XXI", payload: { levels: ["INICIAL", "PRIMARIA", "SECUNDARIA"], description: "Instituto privado laico de Paraná orientado hacia los desafíos del siglo XXI: tecnología, bilingüismo y pensamiento crítico. Ofrece los tres niveles con propuesta actualizada que prepara alumnos para un mundo en transformación acelerada. En la capital de Entre Ríos, con su tradición universitaria y cultural, esta institución forma ciudadanos del mundo con raíces en la identidad litoraleña entrerriana." } },
  { id: "cmq6zbusi00sp12emcqpzydnd", name: "Instituto Sur", payload: { levels: ["INICIAL", "PRIMARIA", "SECUNDARIA"], description: "Instituto privado laico de Paraná con los tres niveles y propuesta educativa comprometida con la calidad académica en la capital entrerriana. Con comunidad activa y docentes especializados, prepara alumnos para el ingreso a la Universidad Nacional del Litoral y otras instituciones de educación superior. Una opción consolidada en el sistema educativo privado de la capital de Entre Ríos." } },
  { id: "cmq6zbume00qv12emgwxu2xus", name: "Paraná High School", payload: { levels: ["INICIAL", "PRIMARIA", "SECUNDARIA"], description: "Institución bilingüe privada de Paraná con propuesta de inmersión en inglés desde el nivel inicial. Con los tres niveles y eje en el bilingüismo real, prepara alumnos para certificaciones internacionales de inglés y para la vida en un mundo globalizado. En la capital entrerriana, es una de las referencias del bilingüismo privado para familias que priorizan la competencia en inglés desde temprana edad." } },
  { id: "cmq6zbv2f00uu12ema2yltqsb", name: "Sarah Eccleston College", payload: { levels: ["INICIAL", "PRIMARIA", "SECUNDARIA"], description: "Institución privada de Paraná que lleva el nombre de la Beata Sarah Eccleston, educadora anglonorteamericana que fundó las Hermanas de la Santa Unión y llegó a Argentina en 1880. Con los tres niveles y la espiritualidad de la Santa Unión —dedicada a la educación de las mujeres jóvenes— es una de las instituciones de mayor tradición en la capital de Entre Ríos, formando varias generaciones de paranaenses con fe y conocimiento." } },
];

async function patchSchool(id, name, payload) {
  const res = await fetch(`${API_BASE}/v1/schools/id/${id}/profile`, {
    method: "PATCH",
    headers: { "content-type": "application/json", "x-admin-key": ADMIN_API_KEY },
    body: JSON.stringify(payload)
  });
  if (res.ok) { console.log(`✅  ${name}`); }
  else { const b = await res.text(); console.error(`❌  ${name} — HTTP ${res.status}: ${b}`); }
}

console.log(`\n🏫  Curando ${updates.length} colegios de Paraná...\n`);
for (const { id, name, payload } of updates) { await patchSchool(id, name, payload); }
console.log("\n✨  Listo.\n");
